### ISSUE TITLE
Broken link in HowToRebuild.txt

### ISSUE THREAD

**Issue by MarkowEduard** [Oleg-N-Cher/OfrontPlus-bootstrap#1]
http://norayr.arnet.am/weblog/2010/02/15/erzahlung-uber-einfach-portieren/

current link

http://norayr.am/weblog/2010/02/15/erzahlung-uber-einfach-portieren/

**Comment by Oleg-N-Cher** [comment]
This repository in general, has lost its relevance, since Ofront+ completely replaces it.

• https://github.com/Oleg-N-Cher/OfrontPlus

I'll probably delete it altogether.

**Comment by MarkowEduard** [comment]
What a pity, I regard it as very useful - especially the HowToRebuild.txt.
I also read the readme of Ofront+ which seems to me much more complex and implements a different language.
I started recently with the archive of ofront1.4 from Templ Josef but could not identically rebuild the system.
I was also impressed by Norayr's achievements.
Generally I think it is a very helpful and useful strategy to translate Oberon, Component Pascal and other not widespread languages to readable C. This could make interfacing many APIs easier and serves as a complementary test branch to compare with e.g. native compiler's results.

**Comment by Oleg-N-Cher** [comment]
I advise you not to take into account the complexity of the compiler. It has slightly increased compared to Ofront, but it implements all the same development approaches in simple safe dialects of Oberon. The A2 or BlackBox compilers, as well as the original ETH Oberon compiler, are much more complex products, than Ofront+, mainly because they generate native machine code.

I don't take the liberty of pointing out the point where complexity begins and simplicity ends. Moreover, most often a programmer is not interested in the complexity of the development tool, but is only interested in the benefits of its use, and according to the tradition of the Oberon paradigm - also full control over all levels of development. We can't do this because we can't get into the C compiler we use, but at the Oberon level, it's easy.

Ofront+ has free support. It has full support for Oberon-2, and in some cases even more informative when displaying runtime errors, as well as a more secure COPY, and many other things.

And this repo has just the beginning of what the modern Ofront+ has become.
